version: 2

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: false

build:
  os: ubuntu-24.04
  tools:
    python: "3.10"

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .